// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATnCkhGl94ZvyiN-sdx0o2DDpUYP1Jcg',
    appId: '1:271755859908:web:968c86d4b6e668a3707691',
    messagingSenderId: '271755859908',
    projectId: 'signytest-24c1e',
    authDomain: 'signytest-24c1e.firebaseapp.com',
    storageBucket: 'signytest-24c1e.appspot.com',
    measurementId: 'G-XE95BGLLNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIyY4zTAd181Ct-fDJg8z7enJIAmCS-9s',
    appId: '1:271755859908:android:2039d22da7a5ce77707691',
    messagingSenderId: '271755859908',
    projectId: 'signytest-24c1e',
    storageBucket: 'signytest-24c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBId5cbE5qR2K9hv05dTmvR1HEy3DFN7S8',
    appId: '1:271755859908:ios:0aafa87b0cef9986707691',
    messagingSenderId: '271755859908',
    projectId: 'signytest-24c1e',
    storageBucket: 'signytest-24c1e.appspot.com',
    androidClientId: '271755859908-gi8qej5ta79uvoaq0qjs8tuibqnkma3f.apps.googleusercontent.com',
    iosClientId: '271755859908-cor2nnmhq0hjo9531u045dfs5fb80790.apps.googleusercontent.com',
    iosBundleId: 'com.example.test12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATnCkhGl94ZvyiN-sdx0o2DDpUYP1Jcg',
    appId: '1:271755859908:web:0f9e0be62b5f4b45707691',
    messagingSenderId: '271755859908',
    projectId: 'signytest-24c1e',
    authDomain: 'signytest-24c1e.firebaseapp.com',
    storageBucket: 'signytest-24c1e.appspot.com',
    measurementId: 'G-GTTE2SCBV9',
  );

}